version: '3.8'

services:
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000
    networks:
      - mern-network

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app/backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/library
      - JWT_SECRET=your_jwt_secret_key_here
      - PORT=5000
    networks:
      - mern-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongodb_data: